FROM python:3.11.7
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN pip install psycopg2-binary
COPY ./logreef /code/logreef
COPY ./tests /code/tests