version: "3.8"
services:
  db:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=logreef
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  test:
    build: 
      dockerfile: Dockerfile-test
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://root:secret@db:5432/logreef
    volumes:
      - ./.env:/code/.env
  server:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://root:secret@db:5432/logreef
    volumes:
      - ./:/code/
      - ./.env:/code/.env
    ports:
      - "8000:80"