FROM python:3.11.7
ARG DB_URL
ARG STORAGE_CONNECTION_STRING
ARG SECRET_KEY
ARG ALGORITHM
ARG ACCESS_TOKEN_EXPIRE_MINUTES
ENV DB_URL=$DB_URL
ENV STORAGE_CONNECTION_STRING=$STORAGE_CONNECTION_STRING
ENV SECRET_KEY=$SECRET_KEY
ENV ALGORITHM=$ALGORITHM
ENV ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN pip install psycopg2-binary
COPY ./logreef /code/logreef
CMD ["uvicorn", "logreef.main:app", "--host", "0.0.0.0", "--port", "80"]